version: '3.4'

services:
  marko-promise-tag:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: "no"
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    
volumes:
  node_modules:
    driver: local
